<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;

class CarsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    // иСПОЛЬзуя директиву ReferenceField (ссылочное поле) будет доп. параметр city который будет формироваться через ReferenceField
    //
    public static function getMap(): array
    {
        $map = [
            'CITY' => new ReferenceField(
                'CITY', 
                CarCityPropertyValuesTable::class, 
                ['=this.CITY_ID' => 'ref.IBLOCK_ELEMENT_ID'] // Идентификатор CITY_ID должен быть равен значению ID из CarCity
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
